<?php
// Include PHPMailer library
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Include autoload.php file generated by Composer
require 'vendor/autoload.php';

// Check if form is submitted
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Validate email and phone number
    $email = $_POST['email'];
    $phone = $_POST['phone'];

    // Display success message immediately
    echo 'Reminder sent successfully to ' . $email;
}
?>
